[2024-06-08T16:08:40.056+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T16:08:40.070+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pg_loader.load_clients manual__2024-06-08T16:08:39.506980+00:00 [queued]>
[2024-06-08T16:08:40.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pg_loader.load_clients manual__2024-06-08T16:08:39.506980+00:00 [queued]>
[2024-06-08T16:08:40.076+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T16:08:40.084+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_clients> on 2024-06-08 16:08:39.506980+00:00
[2024-06-08T16:08:40.087+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T16:08:40.088+0000] {standard_task_runner.py:63} INFO - Started process 1172 to run task
[2024-06-08T16:08:40.088+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pg_loader', 'load_clients', 'manual__2024-06-08T16:08:39.506980+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/load_pg_dag.py', '--cfg-path', '/tmp/tmp3zn37rn9']
[2024-06-08T16:08:40.089+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask load_clients
[2024-06-08T16:08:40.116+0000] {task_command.py:426} INFO - Running <TaskInstance: pg_loader.load_clients manual__2024-06-08T16:08:39.506980+00:00 [running]> on host 945bac6cf142
[2024-06-08T16:08:40.164+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pg_loader' AIRFLOW_CTX_TASK_ID='load_clients' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T16:08:39.506980+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T16:08:39.506980+00:00'
[2024-06-08T16:08:40.165+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T16:08:40.178+0000] {base.py:84} INFO - Using connection ID '***-etl' for task execution.
[2024-06-08T16:08:40.184+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T16:08:40.185+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T16:08:40.190+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pg_loader, task_id=load_clients, run_id=manual__2024-06-08T16:08:39.506980+00:00, execution_date=20240608T160839, start_date=20240608T160840, end_date=20240608T160840
[2024-06-08T16:08:40.227+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T16:08:40.237+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T16:08:40.239+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
